### ISSUE TITLE
Export script

### ISSUE THREAD

**Issue by phoenixr-codes** [allay-mc/scripts#2]
A post script which exports the built add-on to a desired path.

```toml
[scripts]
# ...
post = [
  {
    run = "export.rb",
    with = "ruby",
    args = [
      "dev", # development folder
    ]
]
```

Alternatively, the `--path=PATH` option can be used to specify a custom path. Not providing such value requires the presence of "dev" for development add-on folders or "release" for release add-on folders. The script detects each type of add-on and tries to find the right location depending on the system used (e.g. Android, Windows, Linux, …)
